# ###########################################################################################
# Model: CRDNN with discrete audio representations
# Authors: Luca Della Libera 2024
# ###########################################################################################

run_name: encodec

# Seed needs to be set at top of YAML
seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
data_folder: !PLACEHOLDER
tokens_folder: !PLACEHOLDER
cached_data_folder: !ref <output_folder> # e.g., path/to/cache
train_csv: !ref <save_folder>/trainset_28spk_wav.csv
valid_csv: !ref <save_folder>/validset_wav.csv
test_csv: !ref <save_folder>/testset_wav.csv
splits: [trainset_28spk_wav, validset_wav, testset_wav]
num_valid_speakers: 2
testing: True

# Output folders
output_folder: !ref results/CRDNN/<run_name>/<seed>
save_folder: !ref <output_folder>/save
cache_folder: !name:huggingface_hub.constants.HUGGINGFACE_HUB_CACHE

# Save options
compute_metrics: False
save_audios: False

# Preprocessing parameters
train_remove_if_longer: 60.0  # Seconds
valid_remove_if_longer: 60.0  # Seconds
test_remove_if_longer: 60.0  # Seconds
sorting: random

# Training parameters
num_epochs: 50
grad_accumulation_factor: 1
train_batch_size: 16
valid_batch_size: 1
test_batch_size: 1
dataloader_workers: 4
nonfinite_patience: 10
max_grad_norm: 0.001
precision: fp16
ckpt_interval_minutes: 6000
keep_checkpoints: 1

# Optimizer parameters
lr: 0.0005  # @orion_step1: --lr~"loguniform(0.00001,0.0005)"
weight_decay: 0.01
improvement_threshold: 0.0025
annealing_factor: 0.9
patient: 1

# Codec parameters
codec_type: encodec
sample_rate: 24000  # Should match the tokenizer's sample rate
vocab_size: 1024
num_codebooks: 2
bandwidth: 24.0
kmeans_dataset: LibriSpeech
SSL_layers: [1, 3]  #[1, 3, 7, 12, 18, 23]
tokenizer_save_path: /home/luca/Downloads/SQ-Codec/sqcodec

# Embedding parameters
embedding_dim: 1024
freeze_embedding: False

# Encoder parameters
dropout: 0.1
activation: !name:torch.nn.LeakyReLU
rnn_class: !name:speechbrain.nnet.RNN.LSTM
rnn_layers: 4  # @orion_step1: --rnn_layers~"uniform(1, 4,discrete=True)"
time_pooling_size: 1
rnn_bidirectional: True
rnn_neurons: 256
dnn_blocks: 2
dnn_neurons: 256
cnn_blocks: 2
cnn_channels: (12, 12)
inter_layer_pooling_size: (2, 2)
cnn_kernelsize: (3, 3)

# Modules
embedding: !new:custom_model.Discrete_EmbeddingLayer
    num_codebooks: !ref <num_codebooks>
    vocab_size: !ref <vocab_size>
    emb_dim: !ref <embedding_dim>
    freeze: !ref <freeze_embedding>

attention_mlp: !new:custom_model.AttentionMLP
    input_dim: !ref <embedding_dim>
    hidden_dim: !ref <embedding_dim>

encoder: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <embedding_dim>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    inter_layer_pooling_size: !ref <inter_layer_pooling_size>
    time_pooling: True
    using_2d_pooling: False
    time_pooling_size: !ref <time_pooling_size>
    rnn_class: !ref <rnn_class>
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>
    rnn_re_init: False
    use_rnnp: False

head: !new:torch.nn.Linear
    in_features: !ref <dnn_neurons>
    out_features: !ref <num_codebooks> * <vocab_size>

modules:
    embedding: !ref <embedding>
    attention_mlp: !ref <attention_mlp>
    encoder: !ref <encoder>
    head: !ref <head>

model: !new:torch.nn.ModuleList
    [[!ref <embedding>,
      !ref <attention_mlp>,
      !ref <encoder>,
      !ref <head>]]

# Loss functions
ce_loss: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.0
    allowed_len_diff: 0
    reduction: mean

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9, 0.98)
    eps: 1.e-8
    weight_decay: !ref <weight_decay>

# Schedulers
scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: !ref <patient>

# Token loaders
tokens_loader_in: !new:utils.tokens.TokensLoader
   data_path: !ref <tokens_folder>/input

tokens_loader_out: !new:utils.tokens.TokensLoader
   data_path: !ref <tokens_folder>/output

# Codec
codec: !apply:speechbrain.utils.hparams.choice
  value: !ref <codec_type>
  choices:
    dac: !new:utils.tokenizer_interface.DACTokenizer
      model_type: 24khz
      model_bitrate: 8kbps
      load_pretrained: True
      tag: latest
    encodec: !new:utils.tokenizer_interface.EncodecTokenizer
      source: facebook/encodec_24khz
      save_path: !ref <save_folder>
      sample_rate: !ref <sample_rate>
      bandwidth: !ref <bandwidth>
      flat_embeddings: False
      freeze: True
      renorm_embeddings: False
    mimi: !new:utils.tokenizer_interface.MimiTokenizer
      source: kyutai/mimi
      save_path: !ref <save_folder>
      num_codebooks: !ref <num_codebooks>
      sample_rate: !ref <sample_rate>
    speech_tokenizer: !new:utils.tokenizer_interface.SpeechTokenizerWrapper
      source: fnlp/SpeechTokenizer
      save_path: !ref <save_folder>
      sample_rate: !ref <sample_rate>
    sqcodec: !new:utils.tokenizer_interface.SQCodecTokenizer
      save_path: !ref <tokenizer_save_path>
      checkpoint: ckpt_00190000.pth
      config: config.yaml
      sample_rate: !ref <sample_rate>
    wavtokenizer: !new:utils.tokenizer_interface.WavTokenizerWrapper
      source: novateur/WavTokenizer-medium-music-audio-75token
      save_path: !ref <save_folder>
      checkpoint: wavtokenizer_medium_music_audio_320_24k_v2.ckpt
      config: wavtokenizer_mediumdata_music_audio_frame75_3s_nq1_code4096_dim512_kmeans200_attn.yaml
      sample_rate: !ref <sample_rate>
      freeze: True
    wavlm: !new:utils.tokenizer_interface.DiscreteSSLTokenizer
      save_path: !ref <save_folder>
      ssl_model: !new:speechbrain.lobes.models.huggingface_transformers.wavlm.WavLM
        source: microsoft/wavlm-large
        output_norm: False
        freeze: True
        freeze_feature_extractor: True
        output_all_hiddens: True
        save_path: !ref <save_folder>
      vocoder_repo_id: speechbrain/hifigan-wavlm-k1000-LibriTTS
      kmeans_dataset: !ref <kmeans_dataset>
      num_clusters: !ref <vocab_size>
    hubert: !new:utils.tokenizer_interface.DiscreteSSLTokenizer
      save_path: !ref <save_folder>
      ssl_model: !new:speechbrain.lobes.models.huggingface_transformers.hubert.HuBERT
        source: facebook/hubert-large-ll60k
        output_norm: False
        freeze: True
        freeze_feature_extractor: True
        output_all_hiddens: True
        save_path: !ref <save_folder>
      vocoder_repo_id: speechbrain/hifigan-hubert-k1000-LibriTTS
      kmeans_dataset: !ref <kmeans_dataset>
      num_clusters: !ref <vocab_size>
    wav2vec2: !new:utils.tokenizer_interface.DiscreteSSLTokenizer
      save_path: !ref <save_folder>
      ssl_model: !new:speechbrain.lobes.models.huggingface_transformers.wav2vec2.Wav2Vec2
        source: facebook/wav2vec2-large
        output_norm: False
        freeze: True
        freeze_feature_extractor: True
        output_all_hiddens: True
        save_path: !ref <save_folder>
      vocoder_repo_id: speechbrain/hifigan-wav2vec2-k1000-LibriTTS
      kmeans_dataset: !ref <kmeans_dataset>
      num_clusters: !ref <vocab_size>

# Dataloaders
train_dataloader_kwargs:
    batch_size: !ref <train_batch_size>
    num_workers: !ref <dataloader_workers>
    pin_memory: True
    shuffle: !apply:str.__eq__ [!ref <sorting>, random]

valid_dataloader_kwargs:
    batch_size: !ref <valid_batch_size>
    num_workers: !ref <dataloader_workers>
    pin_memory: True

test_dataloader_kwargs:
    batch_size: !ref <test_batch_size>
    num_workers: !ref <dataloader_workers>
    pin_memory: True

# Performance metrics
ter_computer: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

dnsmos_computer: !name:metrics.dnsmos.DNSMOS
    sample_rate: !ref <sample_rate>

dwer_computer: !name:metrics.dwer.DWER
    model_hub: openai/whisper-small
    save_path: !ref <cache_folder>
    sample_rate: !ref <sample_rate>

wavlm_sim_computer: !name:metrics.spk_sim.SpkSimWavLM
    model_hub: microsoft/wavlm-base-sv
    save_path: !ref <cache_folder>
    sample_rate: !ref <sample_rate>

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <scheduler>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/train_log.txt
