# ############################################################################
# Audio Tokenizer: Mimi
# Extraction: VoiceBank
# Authors: Jarod Duret 2024, Luca Della Libera 2024
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/mimi
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/extraction_log.txt

# Data files
data_folder: !PLACEHOLDER
train_csv: !ref <save_folder>/trainset_28spk_wav.csv
valid_csv: !ref <save_folder>/validset_wav.csv
test_csv: !ref <save_folder>/testset_wav.csv
splits: [trainset_28spk_wav, validset_wav, testset_wav]
num_valid_speakers: 2
cached_data_folder: !ref <output_folder> # e.g., path/to/cache

batch_size: 1
num_workers: 8
src_key: noisy_wav
tgt_key: clean_wav
id_key: id

# Dataloader options
dataloader_opts:
  batch_size: !ref <batch_size>
  shuffle: True
  num_workers: !ref <num_workers>

####################### Model parameters ###########################
# Tokenizer parameters
model_hub: kyutai/mimi
vocab_size: 2048
num_codebooks: 32
sample_rate: 24000
save_embedding: False

tokenizer: !new:utils.tokenizer_interface.MimiTokenizer
  source: !ref <model_hub>
  save_path: !ref <save_folder>
  num_codebooks: !ref <num_codebooks>
  sample_rate: !ref <sample_rate>

tokens_extractor_in: !new:utils.tokens.TokensExtractor
  tokenizer: !ref <tokenizer>
  sample_rate: !ref <sample_rate>
  src_key: !ref <src_key>
  id_key: !ref <id_key>
  dataloader_opts: !ref <dataloader_opts>

tokens_extractor_out: !new:utils.tokens.TokensExtractor
  tokenizer: !ref <tokenizer>
  sample_rate: !ref <sample_rate>
  src_key: !ref <tgt_key>
  id_key: !ref <id_key>
  dataloader_opts: !ref <dataloader_opts>
