name: SpeechBrain pre-commit

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.1
