name: SpeechBrain pre-commit

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.11'
      - uses: pre-commit/action
